-- ==========================================
-- Supabase Schema for School Voting System
-- ==========================================

-- 1. Create candidates table
CREATE TABLE IF NOT EXISTS public.candidates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  position text NOT NULL CHECK (position IN ('SPL', 'ASPL')),
  image_url text,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;

-- Allow public read access to candidates
DROP POLICY IF EXISTS "Allow public read access to candidates" ON public.candidates;
CREATE POLICY "Allow public read access to candidates" 
ON public.candidates FOR SELECT USING (true);

-- Allow admin full access to candidates (adjust criteria as needed, here we allow all operations for simplicity or admin key)
DROP POLICY IF EXISTS "Allow write access to candidates" ON public.candidates;
CREATE POLICY "Allow write access to candidates" 
ON public.candidates FOR ALL USING (true);


-- 2. Create tokens table
CREATE TABLE IF NOT EXISTS public.tokens (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  pin_code text UNIQUE NOT NULL,
  is_used boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  used_at timestamp with time zone
);

ALTER TABLE public.tokens ENABLE ROW LEVEL SECURITY;

-- Allow public read to check token validity
DROP POLICY IF EXISTS "Allow public read access to tokens" ON public.tokens;
CREATE POLICY "Allow public read access to tokens" 
ON public.tokens FOR SELECT USING (true);

-- Allow admin to insert/update tokens
DROP POLICY IF EXISTS "Allow admin operations on tokens" ON public.tokens;
CREATE POLICY "Allow admin operations on tokens" 
ON public.tokens FOR ALL USING (true);


-- 3. Create votes table
CREATE TABLE IF NOT EXISTS public.votes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id bigint REFERENCES public.candidates(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;

-- Deny read access to public for individual votes to keep secrecy
DROP POLICY IF EXISTS "Deny public read access to votes" ON public.votes;
CREATE POLICY "Deny public read access to votes" 
ON public.votes FOR SELECT USING (false);

-- Allow admin read access to counts (or we can use RPC to fetch counts, which is safer)
DROP POLICY IF EXISTS "Allow admin read access to votes" ON public.votes;
CREATE POLICY "Allow admin read access to votes" 
ON public.votes FOR SELECT USING (true);

-- Allow system to insert votes
DROP POLICY IF EXISTS "Allow insert access to votes" ON public.votes;
CREATE POLICY "Allow insert access to votes" 
ON public.votes FOR INSERT WITH CHECK (true);

-- Allow admin to delete votes (for election resets)
DROP POLICY IF EXISTS "Allow delete access to votes" ON public.votes;
CREATE POLICY "Allow delete access to votes" 
ON public.votes FOR DELETE USING (true);


-- ==========================================
-- 4. Secure Transaction Function (RPC)
-- ==========================================
CREATE OR REPLACE FUNCTION public.cast_ballot(
  input_pin text,
  spl_candidate_id bigint,
  aspl_candidate_id bigint
) RETURNS json AS $$
DECLARE
  token_row RECORD;
BEGIN
  -- Select the token and lock the row to prevent concurrent requests
  SELECT * INTO token_row FROM public.tokens 
  WHERE pin_code = input_pin AND is_used = false 
  FOR UPDATE;

  -- Verify token exists and is valid
  IF token_row IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Invalid or already used PIN');
  END IF;

  -- Mark the PIN as used
  UPDATE public.tokens 
  SET is_used = true, used_at = now()
  WHERE pin_code = input_pin;

  -- Record SPL vote if selected
  IF spl_candidate_id IS NOT NULL THEN
    INSERT INTO public.votes (candidate_id) VALUES (spl_candidate_id);
  END IF;

  -- Record ASPL vote if selected
  IF aspl_candidate_id IS NOT NULL THEN
    INSERT INTO public.votes (candidate_id) VALUES (aspl_candidate_id);
  END IF;

  RETURN json_build_object('success', true);
EXCEPTION
  WHEN OTHERS THEN
    RETURN json_build_object('success', false, 'error', SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ==========================================
-- Seed Data (Default Candidates)
-- ==========================================
-- You can run this to pre-load candidates
-- INSERT INTO public.candidates (name, position, image_url) VALUES
-- ('Arjun Kumar', 'SPL', 'https://api.dicebear.com/7.x/adventurer/svg?seed=arjun'),
-- ('Sophia Sen', 'SPL', 'https://api.dicebear.com/7.x/adventurer/svg?seed=sophia'),
-- ('Kabir Dev', 'SPL', 'https://api.dicebear.com/7.x/adventurer/svg?seed=kabir'),
-- -- ('Vikram Shah', 'ASPL', 'https://api.dicebear.com/7.x/adventurer/svg?seed=vikram'),
-- -- ('Ananya Roy', 'ASPL', 'https://api.dicebear.com/7.x/adventurer/svg?seed=ananya'),
-- -- ('Diya Bose', 'ASPL', 'https://api.dicebear.com/7.x/adventurer/svg?seed=diya');


-- ==========================================
-- 5. Supabase Storage Setup (for candidate photos/logos)
-- ==========================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('candidate-images', 'candidate-images', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Allow public select access to candidate-images" ON storage.objects;
CREATE POLICY "Allow public select access to candidate-images"
ON storage.objects FOR SELECT USING (bucket_id = 'candidate-images');

DROP POLICY IF EXISTS "Allow public insert access to candidate-images" ON storage.objects;
CREATE POLICY "Allow public insert access to candidate-images"
ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'candidate-images');

DROP POLICY IF EXISTS "Allow public delete access to candidate-images" ON storage.objects;
CREATE POLICY "Allow public delete access to candidate-images"
ON storage.objects FOR DELETE USING (bucket_id = 'candidate-images');
